title: DigViewer
description: Photo viewer for photographers
repository: opiopan/DigViewer
github:
  owner_name: Hiroshi Murayama
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
- jekyll-sitemap
show_downloads: true
exclude:
- Gemfile
- Gemfile.lock
